runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: main.application

- url: /auth/.*
  script: routes.auth

- url: /api/.*
  script: routes.zoomyapi

- url: /logout
  script: routes.auth

- url: /spotifytest/.*
  script: routes.spotifytest

- url: /(.*)$
  static_files: public/\1
  upload: public/.*$

libraries:
- name: webapp2
  version: latest

includes:
  - env.yaml