runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /z
  script: main.application

- url: /auth/.*
  script: routes.auth

- url: /api/.*
  script: routes.zoomyapi

- url: /logout
  script: routes.auth

- url: /spotifytest/.*
  script: routes.spotifytest

- url: /
  static_files: www/build/index.html
  upload: www/build/index.html

- url: /(.*)$
  static_files: www/build/\1
  upload: www/build/.*$

libraries:
- name: webapp2
  version: latest

includes:
  - env.yaml